### ISSUE TITLE
I've been trying to implement this through Visual Studio

### ISSUE THREAD

**Issue by RexiRexii** [djp952/prebuilt-libcurl#1]
But every time I do, I get the error: "clang.exe" exited with code 1.
Is it possible for you to post an example solution? I've done everything right and I still can't seem to get it working.

My use of STL is set to LLVM libc++ static library
Target API Level is Lollipop 5.1 (android-22)
I did add CURL_STATICLIB to my preprocessor definitions, did my linker -> input right, did my VC++ directory right, i still don't understand why it errors.

**Comment by RexiRexii** [comment]
> RexiRexii

I'd also like to point out I am on ARMV7-x86

**Comment by djp952** [comment]
I'll be honest with you; I did all of this from Windows via the Windows Subsystem for Linux, I never tried to do it via Visual Studio for the *nix platforms.

For anything cURL/*nix, I have found that having an environment where you can run it's configure steps and execute make is seemingly the best way to go? Granted, I did take a lot of steps to "fix things" for Windows, but I honestly didn't change or fix anything for Linux/Android. I would like to help but I don't have the required reference points to draw from. I'm sorry :(

**Comment by RexiRexii** [comment]
Then, could you do me a favor?
Can you post a version of libcurl where it doesn't have any SSL's? I believe that is causing the problems when I try to implement it
I did link the library etc. But when I try to call a cURL function, it cannot build because i am lacking resources for it, I only need a basic curl without SSL, that would be so great if you could do this, thank you.

android-21-armeabi-v7a OR android-22-armeabi-v7a are the ones I can build it with.

**Comment by RexiRexii** [comment]
also you don't have to be sorry for it, i am glad you replied to my comment 👍 😭

**Comment by RexiRexii** [comment]
another request is; could you build zlib for android-21-armeabi-v7a OR android-22-armeabi-v7a?
but instead of making it shared could you make it static?

**Comment by djp952** [comment]
If it becomes necessary, sure, not a big deal, but zlib is pretty easy to incorporate statically into most projects by simply adding the required zlib source code files/headers into any given build?

Some additional context may be helpful here; I am legit fine with helping out on both cURL without SSL and/or statically linked zlib code, I've been there before on both counts and managed to make it work.

I apologize if I missed something along the way that would prevent this seemingly dumb question, and doubly so if it seems "insulting" in any way, but ... what exactly are you trying to accomplish? I legit think if I can better understand what the end goal is I can provide more meaningful advice? Note that I am no longer "invested" in this project and am legit fine with passing on any and all info that would keep it alive; this is not a turf war, it's a legitimate lack of understanding of your end goal.

I'm probably being dumb/obtuse about something here. I want to answer your question(s) as best I can, but I honestly do not understand where this is going? I'm all about "Great minds; fresh ideas"; I'm just currently unsure as to how I am able to contribute to your vision. I do want to help if I can; and I apologize if I'm misunderstanding what is being asked of me?

**Comment by djp952** [comment]
If I am indeed being dumb/obtuse, please feel free to reopen this, but given my desire to close this particular project out and move on from it I am deeming this Issue as seemingly "asked and answered"? I have no intention of flagging the repo as "read-only" (AKA "dead") until it's legitimately in the right place to take that particular action?

I am in a place where I am sincerely looking forward to just "give up and move on", but I do not want to leave anyone hanging in the process if I can avoid it.

**Comment by RexiRexii** [comment]
Nevermind about that, i was mistaken for a while.
I did implement everything just fine, but wolfssl is the current problem now
I do have openssl implemented, if you do not mind, could you make a prebuilt libcurl that uses openssl instead? that'd be lovely.
